import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CartProvider } from "./context/CartContext";
import { AuthProvider } from "./context/AuthContext"; // AuthProvider ইম্পোর্ট করা হয়েছে

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Our Shop - Modern E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider> {/* AuthProvider যোগ করা হয়েছে */}
          <CartProvider>
            {children}
          </CartProvider>
        </AuthProvider> {/* AuthProvider যোগ করা হয়েছে */}
      </body>
    </html>
  );
}
